### ISSUE TITLE
Zwischenfazit - MVP

### ISSUE THREAD

**Issue by tbollmeyer** [Software-Projekt-2022/Dokumentation#32]
MVP milestone nutzen, um Zwischenfazit bzgl. Product & Organisation zu ziehen!

**Product**:
- [ ] Aktueller Stand
- [ ] nächste Schritte
- [x] Herausforderungen
- [x] Vision Endprodukt

**Organisation**:
- [x] Was lief gut?
- [x] Was lief schlecht?
- [ ] Anpassen der Sprints
- [ ] Verbesserungspotentiale

**Comment by mmoedeker** [comment]
unter https://github.com/Software-Projekt-2022/Dokumentation/blob/main/_einleitung/projektorganisation.md sieht man meine Texte. Vision Endprodukt befindet sich in Herausforderungen. Sobald du deine Texte fertig hast können wir gemeinsam drüber schauen.
